[package]
name = "Kai"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0"
log = "0.4"
env_logger = "0.10"
rust-htslib = "0.48"
itertools = "0.10"
flate2 = "1.0"

[[bin]]
name = "kai"
path = "src/main.rs"
